package exceptiondemo2;

public class ExceptionDemo4 {

	public static void main(String[] args) {
		
		
		Abc abc=  new Abc();
		
		abc.checkentry(4);
		

	}
}

class Abc
{
	
	public void checkentry(int i)
	{
      try
      {
    	  if(i>5)
    	  {
    		  throw new Exception("Invalid Entry !");
    	  }
      }
      catch(Exception e)
      {
    	  System.out.println(e.getMessage());
      }
      
      finally
      {
    	  System.out.println("Code Executed !");
      }
	}
	
	
}






//5>i , "Invalid Entry "